# -*- coding: utf-8 -*-
"""lung_cancer_vit_3cls.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sgkKowO8FQjIlxskLstVtKJXbRL4TzVX
"""

!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

!pip install timm
import timm
from fastbook import *
import timm
from fastai.vision.all import *
from timm import create_model
from fastai.vision.learner import _update_first_layer

!pip install kaggle

path = Path('/content/gdrive/MyDrive/lung_image_sets')

all_files= get_image_files(path)

from fastai.vision.augment import contrast
tfms = aug_transforms(size=384,

                      do_flip=False,
                      flip_vert=False,
                      max_rotate=0,
                      max_warp=0,

                      max_lighting=0.70,
                      p_lighting=0.60

                      )

dblock=DataBlock(blocks=(ImageBlock(cls=PILImage),CategoryBlock),
                 splitter=RandomSplitter(valid_pct=0.1),
                 get_y=parent_label,
                 item_tfms=Resize(384,method='squish'),
                 batch_tfms=tfms
)

dls= dblock.dataloaders(all_files,bs=8)

dls.show_batch()

import timm

timm.list_models('vit*')

learn= vision_learner(dls,'vit_tiny_r_s16_p8_384',metrics=accuracy)

learn.lr_find()

learn.fit_one_cycle(50,1.8e-2)

learn.recorder.plot_loss()

interp= ClassificationInterpretation.from_learner(learn)
interp.plot_confusion_matrix()

interp.plot_top_losses(5)

interp.print_classification_report()

learn.save("/content/gdrive/MyDrive/lung_cancer_vit_334")

learn.export("/content/gdrive/MyDrive/lung_cancer_vit_334.pkl")

